--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Homebrew)
-- Dumped by pg_dump version 16.8 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: vape; Type: TABLE; Schema: public; Owner: dev
--

CREATE TABLE public.vape (
    id integer NOT NULL,
    brand character varying(255),
    flavour character varying(255),
    name character varying(255),
    price double precision,
    puffs character varying(255),
    stock integer
);


ALTER TABLE public.vape OWNER TO dev;

--
-- Name: vape_id_seq; Type: SEQUENCE; Schema: public; Owner: dev
--

ALTER TABLE public.vape ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vape_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: vape; Type: TABLE DATA; Schema: public; Owner: dev
--

COPY public.vape (id, brand, flavour, name, price, puffs, stock) FROM stdin;
1	Kros	Mint	Kros	8	8000	50
2	Ignite	Watermelon	V250	15	2500	35
3	Ignite	Banana ice	V150	13	1500	40
4	Elfbar	Strawberry	Elfbar 40k	18	40000	20
5	Lost Mary	Blueberry	Lost Mary Mixer	20	5000	20
\.


--
-- Name: vape_id_seq; Type: SEQUENCE SET; Schema: public; Owner: dev
--

SELECT pg_catalog.setval('public.vape_id_seq', 5, true);


--
-- Name: vape vape_pkey; Type: CONSTRAINT; Schema: public; Owner: dev
--

ALTER TABLE ONLY public.vape
    ADD CONSTRAINT vape_pkey PRIMARY KEY (id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO dev;


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: juanpablolopezorozco
--

ALTER DEFAULT PRIVILEGES FOR ROLE juanpablolopezorozco IN SCHEMA public GRANT ALL ON SEQUENCES TO dev;


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: juanpablolopezorozco
--

ALTER DEFAULT PRIVILEGES FOR ROLE juanpablolopezorozco IN SCHEMA public GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO dev;


--
-- PostgreSQL database dump complete
--

