spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: git@github.com:JPLopezOrozco/config-server-product-crud.git
          host-key-algorithm: ssh-rsa
          private-key: clave privada
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8888

logging:
  level:
    org.springframework.cloud.config: DEBUG
    org.eclipse.jgit: DEBUG